version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    command: python app.py

# docker-compose up --build